export const data = [
    {
        name: "Web Development Bootcamp",
        image: "https://img.freepik.com/premium-vector/web-development-concept-isometric-landing-page-team-develops-optimizes-layout-site_9209-7568.jpg",
        id: 1,
        fees: 1000,
        rating: 3.5,
        duration: "12 weeks",
        certification: "Web Development Certificate",
        level: "Beginner to Intermediate",
        format: "Online",
        desc: 'Build a strong foundation in web development with our comprehensive Web Development Bootcamp. Learn essential skills in HTML, CSS, JavaScript, and more. Get hands-on experience with real-world projects to kickstart your career in web development.',
    },
    {
        name: "Data Science Certification",
        image: "https://www.shutterstock.com/image-photo/data-science-deep-learning-artificial-260nw-1247255884.jpg",
        id: 2,
        fees: 1200,
        rating: 3,
        duration: "16 weeks",
        certification: "Data Science Professional",
        level: "Intermediate",
        format: "Online",
        desc: 'Dive into the world of data science with our Data Science Certification program. Gain expertise in data analysis, machine learning, and statistical modeling. Apply your knowledge to solve complex data problems and make informed business decisions.',
    },
    {
        name: "Digital Marketing Masterclass",
        image: "https://img.freepik.com/premium-photo/digital-design-businessman-show-growth-graph-earning-with-digital-marketing-strategy_35761-549.jpg",
        id: 3,
        fees: 800,
        rating: 4.2,
        duration: "10 weeks",
        certification: "Digital Marketing Expert",
        level: "Intermediate",
        format: "Online",
        desc: 'Master the art of digital marketing with our Digital Marketing Masterclass. Explore strategies for social media marketing, SEO, content marketing, and more. Develop a holistic understanding of digital marketing to drive business success.',
    },
    {
        name: "Project Management Professional (PMP)",
        image: "https://edoxi.com/admin/assets/img/studyhub/An_Introduction_to_Project_Management_Professional_(PMP).webp",
        id: 4,
        fees: 1500,
        rating: 4.5,
        duration: "20 weeks",
        certification: "PMP Certification",
        level: "Advanced",
        format: "Online",
        desc: 'Become a certified Project Management Professional (PMP) with our intensive program. Learn essential project management skills, leadership techniques, and effective communication strategies. Prepare for the PMP exam and advance your career in project management.',
    },
    {
        name: "Graphic Design Fundamentals",
        image: "https://img.freepik.com/premium-photo/computer-screen-with-colorful-paint-it-generative-ai_97167-1066.jpg",
        id: 5,
        fees: 600,
        rating: 5,
        duration: "8 weeks",
        certification: "Graphic Design Foundations",
        level: "Beginner to Intermediate",
        format: "Online",
        desc: 'Unlock your creativity with Graphic Design Fundamentals. Learn the principles of design, use industry-standard tools, and create visually stunning graphics. Explore the world of graphic design and bring your artistic vision to life.',
    },
    {
        name: "Machine Learning Specialization",
        image: "https://media.licdn.com/dms/image/C5112AQG8XW9vllrngw/article-cover_image-shrink_600_2000/0/1520209120370?e=2147483647&v=beta&t=xaTyikW5NV97bWs3nwJu63Z38dyadte9TrgTNqLUXrI",
        id: 6,
        fees: 1400,
        rating: 2.5,
        duration: "18 weeks",
        certification: "Machine Learning Expert",
        level: "Intermediate",
        format: "Online",
        desc: 'Delve into the world of machine learning with our Machine Learning Specialization. Gain expertise in algorithms, data modeling, and artificial intelligence. Apply machine learning techniques to real-world problems and stay ahead in this rapidly evolving field.',
    },
    {
        name: "Cybersecurity Certification",
        image: "https://media.istockphoto.com/id/1331943958/photo/digital-cloud-security-background-concept.jpg?s=612x612&w=0&k=20&c=ktHShoivHgGcXbkgJGUpy6Q5JLYKMGsrbpY0e_4MrSc=",
        id: 7,
        fees: 1100,
        rating: 3,
        duration: "14 weeks",
        certification: "Certified Cybersecurity Professional",
        level: "Intermediate",
        format: "Online",
        desc: 'Secure the future with our Cybersecurity Certification. Learn the latest security techniques, ethical hacking, and risk management. Protect organizations from cyber threats and become a skilled cybersecurity professional.',
    },
    {
        name: "Financial Analyst Program",
        image: "https://blogassets.leverageedu.com/blog/wp-content/uploads/2020/06/12194810/Financial-Analyst-Courses.png",
        id: 8,
        fees: 1300,
        rating: 3,
        duration: "16 weeks",
        certification: "Financial Analyst Certification",
        level: "Intermediate",
        format: "Online",
        desc: 'Master the art of financial analysis with our Financial Analyst Program. Learn financial modeling, budgeting, and forecasting. Analyze financial data to make informed business decisions and excel in the dynamic field of finance.',
    },
    {
        name: "UX/UI Design Course",
        image: "https://www.mindinventory.com/blog/wp-content/uploads/2021/03/mobile-app-design-fundamentals-the-difference-between-UI-and-UX.webp",
        id: 9,
        fees: 900,
        rating: 3.5,
        duration: "12 weeks",
        certification: "UX/UI Design Specialist",
        level: "Intermediate",
        format: "Online",
        desc: 'Immerse yourself in the world of user experience (UX) and user interface (UI) design. Our UX/UI Design Course covers design principles, usability testing, and prototyping. Create intuitive and visually appealing digital experiences.',
    },
    {
        name: "Certified Scrum Master (CSM)",
        image: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F478965569%2F291993007855%2F1%2Foriginal.20200110-045835?w=600&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=6f0d6c7f5b2e0bdf6ca93c2c711323fa",
        id: 10,
        fees: 1200,
        rating: 4.5,
        duration: "14 weeks",
        certification: "Certified Scrum Master",
        level: "Intermediate",
        format: "Online",
        desc: 'Become a Certified Scrum Master and lead agile teams to success. Our CSM program covers agile principles, Scrum framework, and effective collaboration. Gain the skills to facilitate agile processes and drive project success.',
    },
    {
        name: "Business Analytics Certification",
        image: "https://www.simplilearn.com/ice9/free_resources_article_thumb/Business_Analytics_Tools_Used_By_Companies_Today.jpg",
        id: 11,
        fees: 1100,
        rating: 4,
        duration: "18 weeks",
        certification: "Business Analytics Professional",
        level: "Intermediate",
        format: "Online",
        desc: 'Navigate the world of business analytics with our certification program. Analyze business data, create insightful reports, and make data-driven decisions. Acquire the skills needed to thrive in the competitive field of business analytics.',
    },
    {
        name: "Cloud Computing Specialist",
        image: "https://miro.medium.com/v2/resize:fit:640/1*ngkHgQq7ij1NBNr62er3zA.png",
        id: 12,
        fees: 1300,
        rating: 4.5,
        duration: "20 weeks",
        certification: "Cloud Computing Specialist",
        level: "Intermediate",
        format: "Online",
        desc: 'Become a Cloud Computing Specialist and harness the power of cloud technology. Learn about cloud platforms, infrastructure, and deployment strategies. Develop scalable and efficient cloud solutions for modern businesses.',
    },
    {
        name: "Digital Photography Workshop",
        image: "https://www.jdinstitute.edu.in/media/2021/09/Digital-Photography-and-the-dynamics-of-Technology-Innovation-thumbnail.jpg",
        id: 13,
        fees: 500,
        rating: 2.5,
        duration: "6 weeks",
        certification: "Digital Photography Workshop Certificate",
        level: "Beginner",
        format: "Online",
        desc: 'Capture the world through the lens with our Digital Photography Workshop. Learn the art of photography, composition techniques, and digital editing. Unleash your creativity and tell compelling visual stories.',
    },
    {
        name: "Human Resources Management",
        image: "https://thumbs.dreamstime.com/z/hrm-human-resource-management-concept-businessman-hrm-human-resource-management-concept-businessman-203410075.jpg",
        id: 14,
        fees: 1000,
        rating: 3.5,
        duration: "16 weeks",
        certification: "Human Resources Management Certification",
        level: "Intermediate",
        format: "Online",
        desc: 'Excel in Human Resources Management with our comprehensive program. Learn HR strategies, talent management, and employee relations. Develop the skills to lead HR initiatives and contribute to organizational success.',
    },
    {
        name: "Full Stack Developer Program",
        image: "https://images.prismic.io//intuzwebsite/d394de11-2b7f-4a72-a3e0-c876f7356a40_Main.png?w=1200&q=75&auto=format,compress&fm=png8",
        id: 15,
        fees: 1200,
        rating: 5,
        duration: "24 weeks",
        certification: "Full Stack Developer Certification",
        level: "Intermediate to Advanced",
        format: "Online",
        desc: 'Master the skills of a Full Stack Developer with our comprehensive program. Learn front-end and back-end development, database management, and server deployment. Build dynamic and responsive web applications.',
    },
    {
        name: "Digital Entrepreneurship",
        image: "https://blog.hubspot.com/hs-fs/hubfs/image8-2.jpg?width=600&name=image8-2.jpg",
        id: 16,
        fees: 1100,
        rating: 4.2,
        duration: "12 weeks",
        certification: "Digital Entrepreneurship",
        level: "Intermediate",
        format: "Online",
        desc: 'Embark on the journey of digital entrepreneurship. Learn to ideate, validate, and launch digital products and services. Acquire the skills to navigate the dynamic landscape of online business and create your own success story.',
    },
    {
        name: "AI for Everyone",
        image: "https://image.freepik.com/free-vector/illustration-concept-ai-everyone_23-2148299393.jpg",
        id: 17,
        fees: 900,
        rating: 4.5,
        duration: "10 weeks",
        certification: "AI Fundamentals",
        level: "Beginner to Intermediate",
        format: "Online",
        desc: 'Demystify the world of artificial intelligence with our "AI for Everyone" course. Understand the principles of AI, machine learning, and their applications. Explore how AI is transforming industries and shaping the future.',
    },
    {
        name: "Blockchain Fundamentals",
        image: "https://blogs.iadb.org/caribbean-dev-trends/wp-content/uploads/sites/34/2017/12/Blockchain1.jpg",
        id: 18,
        fees: 1300,
        rating: 3.8,
        duration: "14 weeks",
        certification: "Blockchain Basics",
        level: "Intermediate",
        format: "Online",
        desc: 'Delve into the revolutionary technology of blockchain. Learn the fundamentals of blockchain, smart contracts, and decentralized applications. Explore real-world use cases and understand how blockchain is reshaping industries.',
    },
];
