export const data = [
    {
        name: "Web Development Bootcamp",
        image: "https://img.freepik.com/premium-vector/web-development-concept-isometric-landing-page-team-develops-optimizes-layout-site_9209-7568.jpg",
        id: 1,
        fees: 1000,
        raiting : 3.5,
    },
    {
        name: "Data Science Certification",
        image: "https://www.shutterstock.com/image-photo/data-science-deep-learning-artificial-260nw-1247255884.jpg",
        id: 2,
        fees: 1200,
        raiting : 3,

    },
    {
        name: "Digital Marketing Masterclass",
        image: "https://img.freepik.com/premium-photo/digital-design-businessman-show-growth-graph-earning-with-digital-marketing-strategy_35761-549.jpg",
        id: 3,
        fees: 800,
        raiting : 4.2,
    },
    {
        name: "Project Management Professional (PMP)",
        image: "https://edoxi.com/admin/assets/img/studyhub/An_Introduction_to_Project_Management_Professional_(PMP).webp",
        id: 4,
        fees: 1500,
        raiting : 4.5,
    },
    {
        name: "Graphic Design Fundamentals",
        image: "https://img.freepik.com/premium-photo/computer-screen-with-colorful-paint-it-generative-ai_97167-1066.jpg",
        id: 5,
        fees: 600,
        raiting : 5,

    },
    {
        name: "Machine Learning Specialization",
        image: "https://media.licdn.com/dms/image/C5112AQG8XW9vllrngw/article-cover_image-shrink_600_2000/0/1520209120370?e=2147483647&v=beta&t=xaTyikW5NV97bWs3nwJu63Z38dyadte9TrgTNqLUXrI",
        id: 6,
        fees: 1400,
        raiting : 2.5,
    },
    {
        name: "Cybersecurity Certification",
        image: "https://media.istockphoto.com/id/1331943958/photo/digital-cloud-security-background-concept.jpg?s=612x612&w=0&k=20&c=ktHShoivHgGcXbkgJGUpy6Q5JLYKMGsrbpY0e_4MrSc=",
        id: 7,
        fees: 1100,
        raiting : 3,
    },
    {
        name: "Financial Analyst Program",
        image: "https://blogassets.leverageedu.com/blog/wp-content/uploads/2020/06/12194810/Financial-Analyst-Courses.png",
        id: 8,
        fees: 1300,
        raiting : 3,
    },
    {
        name: "UX/UI Design Course",
        image: "https://www.mindinventory.com/blog/wp-content/uploads/2021/03/mobile-app-design-fundamentals-the-difference-between-UI-and-UX.webp",
        id: 9,
        fees: 900,
        raiting : 3.5,
    },
    {
        name: "Certified Scrum Master (CSM)",
        image: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F478965569%2F291993007855%2F1%2Foriginal.20200110-045835?w=600&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=6f0d6c7f5b2e0bdf6ca93c2c711323fa",
        id: 10,
        fees: 1200,
        raiting : 4.5,
    },
    {
        name: "Business Analytics Certification",
        image: "https://www.simplilearn.com/ice9/free_resources_article_thumb/Business_Analytics_Tools_Used_By_Companies_Today.jpg",
        id: 11,
        fees: 1100,
        raiting : 4,
    },
    {
        name: "Cloud Computing Specialist",
        image: "https://miro.medium.com/v2/resize:fit:640/1*ngkHgQq7ij1NBNr62er3zA.png",
        id: 12,
        fees: 1300,
        raiting : 4.5,
    },
    {
        name: "Digital Photography Workshop",
        image: "https://www.jdinstitute.edu.in/media/2021/09/Digital-Photography-and-the-dynamics-of-Technology-Innovation-thumbnail.jpg",
        id: 13,
        fees: 500,
        raiting : 2.5,
    },
    {
        name: "Human Resources Management",
        image: "https://thumbs.dreamstime.com/z/hrm-human-resource-management-concept-businessman-hrm-human-resource-management-concept-businessman-203410075.jpg",
        id: 14,
        fees: 1000,
        raiting : 3.5,
    },
    {
        name: "Full Stack Developer Program",
        image: "https://images.prismic.io//intuzwebsite/d394de11-2b7f-4a72-a3e0-c876f7356a40_Main.png?w=1200&q=75&auto=format,compress&fm=png8",
        id: 15,
        fees: 1200,
        raiting : 5,
    }
];
